// kingdoms.js — World data for the continent of Estranta

const continentName = 'Estranta';
const continentDemonym = 'Estrantic';
const travelDistances = {
  westToEast: '32 days walk',
  northToSouth: '20 days walk',
};

const kingdoms = [
  {
    name: 'Ardrenhold',
    pronunciation: 'AR-dren-hold',
    ruledBy: 'Human',
    population: ['Human'],
    location: 'Western coast',
    environment: 'Lush, green, forest-rich',
    culture: 'Old English / Western European',
    banner: 'Black field with golden-yellow trim and a lion\'s head in the center',
    knownFor: ['Brave and valiant knights', 'Welcoming taverns'],
    notableEvents: [
      'The Festival of the Golden Arrow — an archery competition held in Ealdenford',
      'Annual Harvest Festival in the Goldenfields',
    ],
    locationsOfInterest: [
      { name: "Raven's Perch Lookout", description: "A high tower with breathtaking views, said to be favored by prophetic ravens. Wyverns nest on the nearby cliffs." },
      { name: 'The Ashbound Altar', description: 'A crumbled stone platform on the hillside, blackened by ancient fire. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Oaken Barrow', description: 'A low burial mound swallowed by forest roots. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Hearthstone Inn', description: 'A cozy inn known for heartwarming hospitality and nearby hot springs.' },
      { name: 'The Goldenfields', description: 'Vast fertile fields known for golden wheat and the annual Harvest Festival.' },
      { name: "The Knight's Rest", location: 'Ardrenkeep', description: 'A historic inn and meeting place of legendary knights and adventurers.' },
      { name: 'The Royal Falconry', location: 'Ardrenkeep', description: 'A majestic aviary where the finest falcons are trained for hunting and messaging.' },
      { name: 'Ardrenwood', description: 'A forest inhabited by a goblin tribe threatening nearby villages, especially Hearthmere.' },
      { name: 'The Shadow Cavern', description: "Beneath Raven's Perch Lookout — hides legendary armor once belonging to the Raven Knight. A raven (believed to be the knight's reincarnation) guards it; solve his riddle to claim the armor." },
    ],
    threats: [
      'Goblin scouts in Ardrenwood (near Hearthmere)',
      "Wyverns nesting near Raven's Perch Lookout",
    ],
    cities: [
      { name: 'Ardrenkeep', isCapital: true, description: "Ardrenhold's fortified capital, housing the main keep and throne of the noble king." },
      { name: 'Ealdenford', description: "Meaning 'Old River Crossing.' Built around a historic ford." },
      { name: 'Wulfhelm', description: "Meaning 'Wolf's Helm.' Fortified city known for strength and resilience." },
      { name: 'Aethelstow', description: "'Noble Place.' Known for royal heritage and regal architecture." },
      { name: 'Grimscastel', description: "Meaning 'Grim's Castle.' Marked by a legendary imposing castle." },
    ],
    villages: ['Kinsburg', 'Hearthmere', 'Wyrmwood', 'Brigstow', 'Eorlingstead', 'Alderwood'],
  },

  {
    name: 'Dwynbroch',
    pronunciation: 'DWINE-brock',
    ruledBy: 'Human',
    population: ['Human', 'Dwarf'],
    location: 'Northwestern region',
    environment: 'Mountainous, pine forest-rich, bog-rich',
    culture: 'Celtic / Scottish / Irish',
    banner: 'Green field with yellow accents and a dragon',
    knownFor: ['Music and art', 'Fascination with dragons'],
    notableEvents: [],
    locationsOfInterest: [
      { name: 'The Cairn of Dunan', description: 'A ring of standing stones on a coastal headland. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'Lochvale Arena', description: 'A fighting arena where contestants from across the continent come to fight or bet on fights.' },
      { name: 'The Highland Meadery', description: 'Famous for exquisite honey mead.' },
      { name: 'The Misty Moors', description: 'Expansive moorlands in perpetual mist, home to mystical creatures and ancient spirits. Giant spiders dwell here.' },
      { name: 'The Thornwood Forest', description: 'A dense, thorny enchanted forest with shifting paths and hidden glades. Giant spiders reside within. A reclusive dragon has been sighted here.' },
      { name: "The Minstrel's Meadow", description: 'A tranquil meadow where bards and poets gather to share stories under the stars.' },
      { name: 'The Echoing Hollow', description: 'A secluded glen in Thornwood Forest. An ancient stone altar is a gateway to hidden treasures if the correct echo sequence is replicated.' },
      { name: "The Dragon's Spine Ridge", description: 'A treacherous mountain path with frequent dragon sightings. A dragon egg is hidden in a crevice.' },
      { name: 'The Weeping Waterfall', description: 'A magnificent waterfall concealing a cave lit by bioluminescent moss, housing a chest with lost treasure.' },
    ],
    threats: [
      'Dragon sightings in the Thornwood Forest',
      'Giant spiders in the Misty Moors and Thornwood Forest',
      'Mountain trolls near Lochvale Arena',
    ],
    cities: [
      { name: 'Aberwyn', isCapital: true, description: "Combining 'Aber' (river mouth) and 'Wyn' (fair/white). A picturesque city at a river mouth." },
      { name: 'Lochvale', description: 'Home of the Lochvale Arena.' },
      { name: 'Morvarth', description: "From 'Mor' (sea) and 'Varth' (hill). A coastal city with commanding sea views." },
      { name: 'Glencairn', description: "'Glen' (deep valley) and 'Cairn' (stone monument). Famous for a valley filled with historical cairns." },
      { name: 'Glenvarloch', description: "'Glen' (valley) and 'Varloch' (lake). A city beside a mysterious deep lake." },
    ],
    villages: ['Dalmore', 'Thornwood', 'Braefern', 'Dunleith', 'Glenmire'],
  },

  {
    name: 'Brythwen',
    pronunciation: 'BRITH-wen',
    ruledBy: 'Human',
    population: ['Human'],
    location: 'Southern coast',
    environment: 'Coastal',
    culture: null,
    banner: 'Blue field with a silver whipstaff in the center',
    knownFor: ['Continental hub for traders and merchants', 'Largest marketplace on the continent'],
    notableEvents: [
      'Village of Drunmar stricken with mysterious illness — triggers quest "Barion\'s Blight"',
    ],
    locationsOfInterest: [
      { name: 'Glimwood Castle', description: 'An old abandoned castle hiding a dark secret. Brythwen locals fear it and avoid discussing it.' },
      { name: 'Drunmar village', description: 'A small village on the outskirts stricken with a mysterious illness. Under quarantine.' },
      { name: 'Sapphire Harbor', description: 'A bustling port renowned for sparkling blue waters; popular haven for traders and sailors.' },
      { name: "Sailer's Haven", description: 'A coastal inn known for tales of sea monsters and pirates, with a panoramic ocean view.' },
      { name: 'The Shadow Market', description: 'A secretive marketplace dealing in rare and forbidden goods. A hub for gangs, bandits, pirates, and thieves.' },
      { name: 'Stormwatch Tower', description: 'An ancient tower where watchers predict weather and omens.' },
      { name: "The Wyvern's Windspire", description: 'A high peak where wyverns nest and circle the skies.' },
      { name: 'The Ruins of Windwhisper', location: 'Near Eldenbrook', description: 'An ancient haunted fort. A hidden chamber contains a wind chime that points toward the nearest hidden treasure when rung.' },
      { name: 'The Shattered Citadel of Caldris', description: 'A collapsed tower whose stones lie scattered as if thrown outward by tremendous force. Houses 1 of 12 ancient artifact fragments.' },
    ],
    threats: [
      'Wyverns at the Windspire',
      'Criminal networks operating out of the Shadow Market',
    ],
    cities: [
      { name: 'Brythford', isCapital: true, description: "Brythwen's capital city." },
      { name: 'Eldenbrook', description: "Meaning 'ancient watercourse.' Known for ancient roots and a prominent winding brook." },
      { name: 'Valdara', description: "Evokes 'Val' (valley) and 'Dara' (old lore). A city in a majestic valley steeped in legend." },
      { name: 'Greystone', description: 'Known for renowned architecture and enduring strength.' },
      { name: 'Windhall', description: 'Known for strategic location and resilient people.' },
    ],
    villages: ['Thornwick', 'Brambleton', 'Oakshire', 'Riverwell', 'Meadowford', 'Drunmar'],
  },

  {
    name: 'Nithrond',
    pronunciation: 'NITH-rond',
    ruledBy: 'Elf',
    population: ['Elf'],
    location: 'Southeastern region',
    environment: 'Forested, autumnal',
    culture: null,
    banner: 'Silver crossed arrows over a backdrop of autumn leaves',
    knownFor: ['Elven prowess in archery', 'The Grand Archives — largest library in Estranta'],
    notableEvents: [],
    locationsOfInterest: [
      { name: 'The Silver Hall', description: "The elven grand hall of Nithrond." },
      { name: 'The Grand Archives', description: 'The largest library in all of Estranta. Access restricted to members of the Elven Loremasters Society. Membership requires completing quest "The Secrets of Sareia".' },
      { name: 'Silverspring Meadows', description: 'Tranquil silver-hued meadows.' },
      { name: "Rendrid's Moonlit Bazaar", description: 'A night market open only under the full moon, known for exotic goods and mystical artifacts.' },
      { name: 'The Veil of Vines', description: 'Ancient ruins overtaken by magical vines that orient toward visitors. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Silverstream Bridge', description: 'A bridge over a sparkling stream, known for its picturesque beauty.' },
      { name: 'The Silvermane Meadow', description: 'A clearing home to a rare herd of ethereal silver-maned horses, tameable only by elves.' },
      { name: "Feldghar's Peak", description: 'A mountain once home to a large dragon called Feldghar.' },
      { name: 'The Moonlit Glade', description: 'On full moon nights, an ethereal tree reveals an underground chamber housing an ancient elven crown with unknown powers.' },
      { name: 'The Starfall Burrow', description: 'A crater where meteorites frequently land. A rare Starfall Gem can be found amidst the debris.' },
      { name: 'The Serenity Pool', description: 'A tranquil pool that reflects stars above. Bathing during a lunar eclipse reveals a vision of where a powerful staff is buried.' },
    ],
    threats: [],
    restrictions: ['Grand Archives access requires Elven Loremasters Society membership'],
    cities: [
      { name: 'Thalorion', isCapital: true, description: 'A majestic city in a crescent valley, buildings carved from shimmering white stone and grown from enchanted roots.' },
      { name: 'Sylvaen', description: 'Built into and around towering silver-bark trees, known for elevated walkways and glowing crystal lanterns.' },
      { name: 'Virelysar', description: 'A city of scholars and spellweavers where moonlight reflects off mirrored lakes.' },
      { name: 'Caeleth', description: 'Surrounded by autumnal forests, famed for amber-leafed gardens and moonstone roads.' },
      { name: 'Namorelith', description: 'Perched on cliffs above the ocean, known for wind harps playing melodies through natural stone arches.' },
    ],
    villages: ['Elmyralen', 'Firaelis', 'Tirwynn Hollow', "Liraen's Cross", 'Thandelmere'],
  },

  {
    name: 'Sivanrift',
    pronunciation: 'SIGH-van-rift',
    ruledBy: 'Elf',
    population: ['Elf', 'Human'],
    location: 'Southwestern region',
    environment: 'Varied — gardens, canyon networks, forest',
    culture: null,
    banner: 'Yellow field with an intricate white flower (the sacred elven flower of life)',
    knownFor: ['Rare plants grown nowhere else in the world', 'Grand Gardens in the capital'],
    notableEvents: [
      'The Cursed Forest — triggers quest "The Sword of Ithalia" when explored',
    ],
    locationsOfInterest: [
      { name: 'The Grand Gardens of Sivanrift', description: "The gardens in the capital's town square, growing rare plants found nowhere else in the world." },
      { name: 'The Cursed Forest', description: "A forest cursed centuries ago by the elven witch Ithalia. A sword stuck in a tree stump begins the quest 'The Sword of Ithalia' when touched." },
      { name: 'The Echoing Canyons', description: 'A network of canyons with unique acoustics, where winds create haunting melodies.' },
      { name: 'The Thornward Pillars', description: 'Seven carved stone pillars in a semicircle, one position deliberately empty. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Willowmere Pond', description: 'A serene pond surrounded by willow trees, believed to be a place of healing and reflection.' },
      { name: 'The Twilight Vineyards', description: 'Expansive vineyards producing the finest wines, harvested under the twilight sky.' },
      { name: 'The Moonlit Grove', description: 'A mystical grove inhabited by luminescent fae creatures.' },
      { name: 'The Shrouded Caves', description: 'Near the Cursed Forest. Deep within, a crystal formation radiates mystical energy, offering enhanced magical essence to those who touch it.' },
    ],
    threats: [
      'Tensions between human and elven populations',
    ],
    cities: [
      { name: 'Myrthill', isCapital: true, description: 'A radiant city of silverwood towers and marble courtyards, centered around the Grand Gardens. A symbol of inter-racial harmony — at least on the surface.' },
      { name: 'Aurelwyn', description: 'A port city along a crescent bay, thriving on trade in exotic wines, enchanted textiles, and rare herbs.' },
      { name: 'Talandras', description: 'A city straddling rivers and waterfalls, known for translucent bridges and the hidden Temple of the Water Moon.' },
      { name: 'Velendar', description: 'A cultural hub for musicians, poets, and lorekeepers, with amphitheaters, galleries, and moonlit concerts.' },
      { name: 'Iriandel', description: 'Constructed along the cliffside above the Echoing Canyons. Uses natural acoustics in both art and defense.' },
    ],
    villages: ['Willowfen', 'Duskwatch', "Elowen's Field", 'Halorin Cross', 'Rivensong'],
  },

  {
    name: 'Naradreth',
    pronunciation: 'NAR-ah-dreth',
    ruledBy: 'Elf',
    population: ['Elf'],
    location: 'Eastern coast',
    environment: 'Coastal',
    culture: null,
    banner: 'Orange field with a red sun in the middle',
    knownFor: ['Hostile to strangers, especially non-elves', 'On the brink of civil war'],
    notableEvents: [
      'Civil war imminent between the Twelve Great Houses',
      'Triggers quest "Eratrid\'s Lament"',
      'Triggers quest "Neialor\'s Feline Dilemma" (cat NPC found in any village)',
      'Triggers quest "The Lovers\' Plight" (inter-racial couple in hiding)',
    ],
    locationsOfInterest: [
      { name: 'Sunspire Tower', description: 'An ancient observatory where elves study stars and celestial movements.' },
      { name: 'The Sunken Shrine of Vaeryn', description: 'A partially submerged structure carved in a script that predates all known elven writing. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Singing Springs', description: 'Springs that emit melodic tones when their waters are disturbed.' },
      { name: 'The Sunstone Citadel', description: 'A majestic elven fortress bathed in sunlight, known for impressive architecture and history.' },
      { name: "The Emerald Serpent's Lair", description: 'A hidden cave where a wise but dangerous dragon resides.' },
      { name: 'Twilight Mirror Lake', description: 'A hidden lake reflecting stars even during the day. A submerged elven shrine guards an ancient tome with lost elven lore and a spell granting temporary underwater breathing.' },
      { name: 'Eclipse Grove', description: 'A sacred grove that comes alive during lunar and solar eclipses, revealing a hidden path.' },
    ],
    threats: [
      'Hostile to outsiders — especially non-elves',
      'Imminent civil war between the Twelve Great Houses',
    ],
    restrictions: ['Outsiders rarely welcomed; most never see beyond the outer walls of Velra\'syl'],
    cities: [
      { name: "Velra'syl", isCapital: true, description: "The capital, divided into twelve noble districts each ruled by one of the Twelve Great Houses. The Circle of Spires at its center is where the houses govern. Outsiders are rarely welcome." },
      { name: 'Ilryndor', description: 'A shadowed harbor city with black sails and moonlit docks, heavily patrolled by the Silent Guard. Home to an elite naval academy.' },
      { name: "Draes'ythil", description: 'The "Sister of Silence." A seat of old magic and home to seers. All communication here is done via telepathic glyphs — no one speaks aloud.' },
    ],
    villages: ["Tiryll's Hollow", "Mythren's Gate", 'Vaerlyn Reach'],
  },

  {
    name: 'Feldarún',
    pronunciation: 'FELL-dar-rune',
    ruledBy: 'Dwarf',
    population: ['Dwarf'],
    location: 'Central region (mountainous)',
    environment: 'Hidden in mountainous terrain',
    culture: null,
    banner: 'A hammer and anvil on a background of stone grey',
    knownFor: ['Mining heritage', 'Master craftsmanship', 'Hostile to strangers, especially non-dwarves'],
    notableEvents: [],
    locationsOfInterest: [
      { name: 'The Murkridge Hollows', description: 'A vast underground cave network full of goblins and cave trolls. Great riches hidden within for those brave enough.' },
      { name: 'The Irondeep Catacombs', description: 'Passages carved into the mountain far below dwarven-made tunnels, by builders of unknown origin. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Emberheart Tavern', description: 'Famous for fiery spiced cuisine and a warm hearth, but wary of outsiders and non-dwarves.' },
      { name: 'The Ironbell Forge', description: 'A renowned forge where master blacksmiths create legendary dwarven weapons and artifacts.' },
      { name: 'The Ironback Mountains', description: 'Mountain ranges where many trolls and giants roam.' },
      { name: 'The Glimmering Depths', description: "Hidden in the Ironback Mountains. A crystal pool at its deepest point reflects visions of distant places and events." },
    ],
    threats: [
      'Goblins and cave trolls in the Murkridge Hollows',
      'Trolls and giants in the Ironback Mountains',
    ],
    restrictions: ['Dwarves do not take kindly to strangers, especially non-dwarves'],
    cities: [
      { name: 'Khúralgron', isCapital: false, description: 'A grand forge-city carved into a volcanic caldera. Molten rivers fuel legendary smithies day and night.' },
      { name: 'Darakthul', description: 'Known as the "Iron Crown of the East." Built atop a jagged peak, ringed with obsidian battlements.' },
      { name: 'Brondrak Kazel', description: 'Translates to "Hammer\'s Heart." A deep-delving citadel where the Great Anvil of the Mountain King rests.' },
      { name: 'Vurndrim', description: 'Famed for echoing halls and deep-drum festivals, where every corridor carries ancient songs.' },
      { name: 'Tharnhold', description: "Half fortress, half temple. Guards the oldest relics of dwarfkind in vaulted stone crypts." },
    ],
    villages: ['Stonebraith', "Molgrin's Deep", 'Emberstead', 'Grummveir', 'Kaerbryn Hollow'],
  },

  {
    name: 'Wistravael',
    pronunciation: 'WIST-ruh-vale',
    ruledBy: 'Dwarf',
    population: ['Dwarf'],
    location: 'Northern region',
    environment: 'Mountainous, forested',
    culture: null,
    banner: 'A stout mountain overlaid with a starry sky on a dark blue field',
    knownFor: ['Dwarven architecture', 'Connection to earth and heavens'],
    notableEvents: [],
    locationsOfInterest: [
      { name: "The Dwarven King's Keep", description: 'A marvel of dwarven architecture and ingenuity.' },
      { name: 'The Starfall Cradle', description: 'A depression ringed by shaped stones, the earth inside faintly warm. Something arrived here deliberately long ago. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Shrouded Glade', description: 'Deep in the forest — a crashed ship overgrown with vines and foliage. No one knows how it got there. Said to be the home of a mysterious entity.' },
      { name: 'The Vordynmire Caverns', description: 'Deep within the Vordynmire mountains. Home to rare minerals, illuminated by fiery fissures, but also a feared troll.' },
      { name: 'The Alestone Mines', description: 'Mines known for a unique stone that enhances the flavor of ale brewed nearby.' },
      { name: 'The Gilded Anvil', description: 'A famous dwarven blacksmith shop known for exquisite jewelry and decorative metalwork.' },
      { name: 'The Drakeling Pass', description: 'A narrow pass guarded by adolescent but fierce dragons.' },
      { name: 'The Celestial Observatory', description: 'A forgotten observatory atop the highest peak. A celestial map reveals the location of hidden star metal — a rare substance for weapons of unparalleled sharpness.' },
      { name: 'The Dreaming Cavern', description: 'Beneath the Alestone Mines. A dream crystal at its center allows the holder to enter a dream state for insight into future events or distant places.' },
    ],
    threats: [
      'Dragons guarding the Drakeling Pass',
      'Troll in the Vordynmire Caverns',
      'Mysterious entity in the Shrouded Glade',
    ],
    cities: [
      { name: 'Durkendal', isCapital: true, description: 'Built beneath the Mountain of Stars. Known for its vast observatory and underground council halls.' },
      { name: 'Tharnvyr', description: 'A forge-city glowing with red fissures and smoke plumes, crafting legendary weapons and star-metal armaments.' },
      { name: 'Vordrun Keep', description: 'A heavily fortified city carved into a sheer cliff, guarding the pass into the inner kingdom.' },
      { name: 'Stonewake', description: 'A city of scholars and miners, walls engraved with glowing rune maps of the stars and earth.' },
      { name: 'Kragmire Hold', description: 'Built above a natural magma river, specializing in enchanted jewelry and tools forged from obsidian and infused crystals.' },
    ],
    villages: ['Flinthollow', 'Silverdeep', "Bramgar's Rest", 'Hearthglen', 'Wyrshade'],
  },

  {
    name: 'Orindroth',
    pronunciation: 'OR-in-droth',
    ruledBy: 'Elf',
    population: ['Elf'],
    location: 'Central region (outside the mountains)',
    environment: 'Dense, ancient forest — the entire kingdom lies within the forest',
    culture: null,
    banner: 'Shades of green, showing a sacred tree in the center',
    knownFor: ['Sacred trees with mystical properties', 'Forest shrouded in mystery and easy to become lost in'],
    notableEvents: [
      'Triggers quest "The Whispering Woods"',
    ],
    locationsOfInterest: [
      { name: 'The Forest of Orindroth', description: 'The entire kingdom lies within this ancient forest. Tricky to navigate. Hides many secrets. Sacred trees with unique mystical properties. Giant spiders and forest trolls dwell here.' },
      { name: 'The Eldertree Threshold', description: 'A stone archway standing alone with no wall attached. Animals refuse to pass through it. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Wandering Wyvern Inn', description: 'A renowned inn for travelers and adventurers, filled with tales of daring exploits.' },
      { name: 'The Eldertree Circle', description: 'A sacred grove where ancient trees form a circle, believed to be a place of powerful magic.' },
      { name: 'The Moonstone Gallery', description: 'An art gallery displaying exquisite elven artwork — paintings and sculptures.' },
      { name: 'The Eldertree Sanctuary', description: 'Deep in the forest. Ancient trees form a protective circle around an ancient elven altar.' },
      { name: 'The Moonstone Hollow', description: 'Glows under the moonlight. A moonstone obelisk reveals a hidden compartment containing an elven cloak that grants the ability to blend into natural surroundings.' },
    ],
    threats: [
      'Giant spiders in the forest',
      'Forest trolls',
      'Easy to become lost in the dense forest',
    ],
    cities: [
      { name: 'Elarien', isCapital: false, description: 'The spiritual heart of Orindroth, built within a ring of ancient towering trees. A haven for druids and forest sages.' },
      { name: 'Valorin', description: 'A canopy city woven into the treetops, connected by rope bridges and vine-lifts.' },
      { name: 'Ilietha', description: 'Hidden beneath a massive hollowed tree. A place of meditation, dreams, and communion with forest spirits.' },
      { name: 'Tirelyn Reach', description: 'A cliffside outpost overlooking the forest canopy. Moonlight rituals and star charting performed here.' },
      { name: "Norowynn's Veil", description: 'A veiled grove obscured by illusion magic. Meeting place of the Circle of Eldertrees — the hidden rulers of Orindroth.' },
    ],
    villages: ['Larethwyn', "Feyran's Nest", 'Thiriel Glen', "Mireth's Bloom", 'Wendralis Shade'],
  },

  {
    name: 'Rendarost',
    pronunciation: 'REN-dar-ost',
    ruledBy: 'Dwarf',
    population: ['Dwarf'],
    location: 'Far northern region',
    environment: 'Harsh, snowy, arctic',
    culture: null,
    banner: 'White snowflake on an icy blue field, bordered with white fur',
    knownFor: ['Hardiness and resilience in cold climate', 'The Dwarven Archives (open to public)', 'Frost ale brewed by a secret method'],
    notableEvents: [
      'Triggers quest "The Great Void" — Brindon found at the Dwarven Archives',
    ],
    locationsOfInterest: [
      { name: 'Healing Hot Springs', description: 'Hidden in the snowy mountains. Rare hot springs with healing properties.' },
      { name: 'The Frostbound Sanctum', description: 'A structure encased in glacier ice, its domed roof visible from outside. Frost wyrms guard the area. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Duskstone Vault', description: 'A sealed granite chamber in the northern forest, warm to the touch in all seasons. Houses 1 of 12 ancient artifact fragments.' },
      { name: 'The Dwarven Archives of Rendarost', description: 'A large library full of dwarven lore, open to the public. Brindon can be found here.' },
      { name: 'The Frostbrew Tavern', description: 'Famous for frost ale, brewed using a secret method known only to the dwarves of Rendarost.' },
      { name: 'The Frostflower Fields', description: 'Fields of rare frost-resistant flowers with unique properties, blooming even in harsh winters. Ice wyrms lurk beneath.' },
      { name: 'The Frost Troll Ridge', description: 'A mountainous region home to frost trolls and frost giants.' },
      { name: "The Frost Wyrm's Lair", description: 'Icy caverns where frost wyrms slumber and hoard treasures.' },
      { name: 'The Frostfire Chasm', description: 'A hidden chasm in the Frostflower Fields, warm despite surrounding snow. Contains a frozen flame artifact usable in a potion granting resistance to extreme temperatures.' },
      { name: 'The Icebound Vault', description: 'Near the Frost Troll Ridge. An ice-sealed vault containing an ancient dwarven artifact.' },
    ],
    threats: [
      'Frost giants in the Frost Troll Ridge',
      'Ice wyrms in the Frostflower Fields',
      'Frost trolls in the Frost Troll Ridge',
      "Frost wyrms in the Frost Wyrm's Lair",
    ],
    cities: [
      { name: 'Kragmoor', isCapital: false, description: 'A fortress-city tunneled into a frozen cliff face, selling frost-forged weapons only to kin.' },
      { name: 'Dravundar', description: 'An underground city of glowing ice crystals and heated forges, protected by massive rune-sealed doors.' },
      { name: 'Iskroldir', description: 'Built into a glacial shelf, using geothermal vents for warmth. Halls steam and shimmer with heat and frost alike.' },
      { name: 'Thuldrenheim', description: 'A city-temple dedicated to mountain spirits. Runesingers chant in the deep to ward off avalanches and frost-wyrms.' },
      { name: "Varkol's Crown", description: "Highest of Rendarost's cities, near the summit of the Skyteeth Range. Watchtowers pierce the clouds." },
    ],
    villages: ['Brynfrost', 'Tarnshield', 'Frostmere Hold', 'Hearthvault', 'Icevein Hollow'],
  },
];
